from flask import Flask, jsonify
from google.cloud import storage, bigquery
import os

app = Flask(__name__)

@app.route('/')
def hello():
    return jsonify({
        "message": "Welcome to the GitHub Events Explorer!",
        "endpoints": {
            "/upload": "Upload a sample report to Cloud Storage",
            "/query": "Top 10 most active GitHub event types",
            "/summary": "GitHub events summary by year"
        }
    })

@app.route('/upload')
def upload_file():
    storage_client = storage.Client()
    bucket_name = os.environ.get('BUCKET_NAME')
    if not bucket_name:
        return jsonify({"error": "BUCKET_NAME environment variable is not set."}), 500
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob('github_report.txt')
    blob.upload_from_string('GitHub Events Analysis Report - Generated by Cloud Run')
    return jsonify({
        "status": "success",
        "message": f"File uploaded to {bucket_name}/github_report.txt"
    })

@app.route('/query')
def query_top_events():
    client = bigquery.Client()
    query = """
        SELECT type, COUNT(*) as event_count
        FROM `githubarchive.day.20240101`
        GROUP BY type
        ORDER BY event_count DESC
        LIMIT 10
    """
    query_job = client.query(query)
    results = query_job.result()
    events = [{"type": row.type, "count": row.event_count} for row in results]
    return jsonify({
        "title": "Top 10 GitHub Event Types (Jan 1, 2024)",
        "data": events
    })

@app.route('/summary')
def summary():
    client = bigquery.Client()
    query = """
        SELECT
            type,
            COUNT(*) as total_events,
            COUNT(DISTINCT actor.login) as unique_users
        FROM `githubarchive.day.20240101`
        GROUP BY type
        ORDER BY total_events DESC
        LIMIT 5
    """
    query_job = client.query(query)
    results = query_job.result()
    summary_data = [
        {
            "event_type": row.type,
            "total_events": row.total_events,
            "unique_users": row.unique_users
        }
        for row in results
    ]
    return jsonify({
        "title": "GitHub Events Summary with Unique Users (Jan 1, 2024)",
        "data": summary_data
    })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)